global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'rust-ratelimit'
    static_configs:
      - targets: ['ratelimit:8080']
    scrape_interval: 10s
    metrics_path: '/metrics'
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'redis-persecond'
    static_configs:
      - targets: ['redis-persecond:6379']
    scrape_interval: 30s