// This file is auto-generated by the build script
// Include the generated protobuf code

pub mod envoy {
    pub mod service {
        pub mod ratelimit {
            pub mod v3 {
                // Include the generated protobuf code
                include!(concat!(env!("OUT_DIR"), "/envoy.service.ratelimit.v3.rs"));
            }
        }
    }
}

pub mod ratelimit {
    pub mod config {
        pub mod v3 {
            // Include the generated config protobuf code
            include!(concat!(env!("OUT_DIR"), "/ratelimit.config.v3.rs"));
        }
    }
}

// Re-export the main types for easy access
pub use envoy::service::ratelimit::v3::{
    RateLimitRequest, RateLimitResponse, RateLimitDescriptor, RateLimitDescriptorEntry,
    rate_limit_response::{DescriptorStatus, RateLimit, Code as ResponseCode},
    rate_limit_service_server::{RateLimitService, RateLimitServiceServer},
};
